#Balkon's WeaponMod 1.4.6 v1.10.3
#Properties file

#Set the following values to "true" to use them in your game, 
#and "false" if you don't want them.
#If you disable the knife, you disable the bayonet too.

cannon-block-damage=true
dynamite-block-damage=true
can-throw-knife=true
can-throw-spear=true
#Turn this to "owner" to allow only the thrower/shooter of the projectile to pick the item up. If set to "all" everyone can pick the item up. Only affects projectiles that can be picked up.
#projectile-accessibility=owner
projectile-accessibility=all

spear=true
halberd=true
battleaxe=true
warhammer=true
knife=true
javelin=true
musket=true
crossbow=true
blowgun=true
dynamite=true
flail=true
firerod=true
cannon=true
blunderbuss=true
dummy=true
boomerang=true

#Entity ID's
#Since v9.0 you cannot leave the entity ID's 0 anymore.
#Client- and server-side entity ID's MUST be equal.

spear-entity=2300
knife-entity=2301
flail-entity=2302
dynamite-entity=2303
javelin-entity=2304
bullet-entity=2305
dart-entity=2306
bolt-entity=2307
cannon-entity=2308
cannonball-entity=2309
shot-entity=2310
dummy-entity=2311
boomerang-entity=2312

#Item ID's
#Since v9.0 you cannot leave the item ID's 0 anymore.
#Client- and server-side item ID's MUST be equal.

#Spear
wood-spear-id=11520
stone-spear-id=11521
iron-spear-id=11522
diamond-spear-id=11523
gold-spear-id=11524

#Halberd
wood-halberd-id=11525
stone-halberd-id=11526
iron-halberd-id=11527
diamond-halberd-id=11528
gold-halberd-id=11529

#Battleaxe
wood-battleaxe-id=11530
stone-battleaxe-id=11531
iron-battleaxe-id=11532
diamond-battleaxe-id=11533
gold-battleaxe-id=11534

#Warhammer
wood-warhammer-id=11535
stone-warhammer-id=11536
iron-warhammer-id=11537
diamond-warhammer-id=11538
gold-warhammer-id=11539

#Knife
wood-knife-id=11540
stone-knife-id=11541
iron-knife-id=11542
diamond-knife-id=11543
gold-knife-id=11544

#Flail
wood-flail-id=11545
stone-flail-id=11546
iron-flail-id=11547
diamond-flail-id=11548
gold-flail-id=11549

#Javelin
javelin-id=11550

#Musket
musket-id=11551
musketbayonet-id=11552
musket-ironpart-id=11553
bullet-id=11554

#Crossbow
crossbow-id=11555
bolt-id=11556

#Blowgun
blowgun-id=11557
dart-id=11558

#Dynamite
dynamite-id=11559

#Fire Rod
firerod-id=11560

#Cannon
cannon-id=11561
cannonball-id=11562

#Blunderbuss
blunderbuss-id=11563
shot-id=11564
blunder-ironpart-id=11565

#Training Dummy
dummy-id=11566

#Overall
gun-stock-id=11567

#Boomerang
wood-boomerang-id=11568
stone-boomerang-id=11569
iron-boomerang-id=11570
diamond-boomerang-id=11571
gold-boomerang-id=11572

#Reload durations
musket-reloadtime=30
blunderbuss-reloadtime=20
crossbow-reloadtime=15
blowgun-reloadtime=10
